import Head from 'next/head'
import { Inter } from 'next/font/google'
import Card from '@/components/Card'
const inter = Inter({ subsets: ['latin'] })
import styles from "@/styles/Form.module.css"
import Link from 'next/link'
import NumberInput from '@/components/NumberInput'
import { useState } from 'react'

export default function Form() {

  const [qtdDoors, setQtdDoors] = useState(3);
  const [gift, setGift] = useState(1);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.form}>
        <div>
          <Card bgcolor='#C0392C'>
            <h1>Monty Hall</h1>
          </Card>
          <Card >
            <NumberInput
              text="Qtde Portas?"
              value={qtdDoors}
              onChange={(newQtde) => setQtdDoors(newQtde)} />
          </Card >
        </div>
        <div>
          <Card>
          <NumberInput
              text="Porta com Presente?"
              value={gift}
              onChange={(gifting) => setGift(gifting)} />
          </Card>
          <Card bgcolor='#28A085'>
            <Link href={`/game/${qtdDoors}/${gift}`}>
              <h2 className={styles.link} >Iniciar</h2>
            </Link>
          </Card>
        </div>
      </main>
    </>
  )
}

